@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' LAYOUT_WITH_LEGEND()

title Схема взаимодействия систем

Person(Клиент, Заказчик)

' Системы
System_Boundary(ЕРП, "1C:ERP") {
    Container(ЕРП_Заявки, "Подача заявок на изменение", "")    
}
' System_Boundary(ЗУП, "1C:ЗУП") {
'     Container(ЗУП_Заявки, "Подача заявок на изменение", "")
' }

' System(Трекер, "1C:Трекер")
System_Boundary(Трекер, "1C:Трекер") {
}

System_Ext(ШинаДанных, "RabbitMQ")

' Связи
Rel(Клиент, ЕРП_Заявки, "Подача заявки")
Rel(ЕРП_Заявки, ШинаДанных, "Заявки на изменение")
Rel(ШинаДанных, Трекер, "Заявки на изменение")
' Rel(Клиент, ЗУП_Заявки, "Подача заявки")
' Rel(ЗУП_Заявки, ШинаДанных, "Заявки на изменение")

Rel(Трекер, ШинаДанных, "Программные продукты")
Rel(ШинаДанных, ЕРП_Заявки, "Программные продукты")
' Rel(ШинаДанных, ЗУП_Заявки, "Программные продукты")


' Расположение
'Lay_U(ЕРП, Трекер)

@enduml