@startuml

!define v8_PUML https://raw.githubusercontent.com/ovcharenko-di/1ce-icons-for-plantuml/main/dist
!include v8_PUML/common.puml
!include v8_PUML/v8_Catalog.puml
!include v8_PUML/v8_BusinessProcess.puml
!include v8_PUML/v8_InfoRg.puml
!include v8_PUML/v8_DataProcessor.puml
!include v8_PUML/v8_Task.puml
!include v8_PUML/v8_Const.puml
!include v8_PUML/v8_Enum.puml

title Схема метаданных конфигураций

caption ___

package Трекер <<Rectangle>> #ffff99 {

    _Перечисление(СтатусыЗаявкиНаИзменение, "Статусы заявки на изменение")
    
    _Справочник(Пользователи)

    _Справочник(ПрограммныеПродукты, "Программные продукты")
    
    _Справочник(РолиИсполнителей, "Роли исполнителей")
    
    _БизнесПроцесс(бпЗаявкаНаИзменение, "Заявка на изменение")
    бпЗаявкаНаИзменение : ПрограммныйПродукт
    бпЗаявкаНаИзменение : Статус
    бпЗаявкаНаИзменение : Аналитик 

    _Задача(ЗадачаИсполнителя, "Задача исполнителя")
    ЗадачаИсполнителя : БизнесПроцесс
    ЗадачаИсполнителя : Роль
    ЗадачаИсполнителя : Исполнитель

    _РегистрСведений(рсТрудозатраты, "Трудозатраты по заявкам на изменение")
    рсТрудозатраты : Заявка
    рсТрудозатраты : Задача
    рсТрудозатраты : Исполнитель
    рсТрудозатраты : Трудозатраты

    _РегистрСведений(рсПараметрыРМК, "Параметры RabbitMQ")
    
    _РегистрСведений(рсИсполнителиЗадач, "Исполнители задач")
    рсИсполнителиЗадач : Роль
    рсИсполнителиЗадач : Исполнитель
    
}

package Трекер-клиент <<Rectangle>> #b3c6ff {

    v8_Catalog(клПрограммныеПродукты, "Программные продукты")
    'клПрограммныеПродукты : Ссылка

    _Константа(клТекущийПрограммныйПродукт, "Текущий программный продукт")

    v8_DataProcessor(клОбрЗаявкаНаИзменение, "Подача заявки на изменение")
    клОбрЗаявкаНаИзменение : ПрограммныйПродукт

    v8_InfoRg(клРсПараметрыРМК, "Параметры RabbitMQ")

} 

ПрограммныеПродукты-->бпЗаявкаНаИзменение
СтатусыЗаявкиНаИзменение-->бпЗаявкаНаИзменение
Пользователи-->бпЗаявкаНаИзменение

бпЗаявкаНаИзменение-->ЗадачаИсполнителя
Пользователи-->ЗадачаИсполнителя
РолиИсполнителей-->ЗадачаИсполнителя

бпЗаявкаНаИзменение-->рсТрудозатраты
ЗадачаИсполнителя-->рсТрудозатраты
Пользователи-->рсТрудозатраты

РолиИсполнителей-->рсИсполнителиЗадач
Пользователи-->рсИсполнителиЗадач


клПрограммныеПродукты-->клОбрЗаявкаНаИзменение
клПрограммныеПродукты-->клТекущийПрограммныйПродукт

@enduml